### ISSUE TITLE
Latest nightly build download link broken!

### ISSUE THREAD

**Issue by unalsurmeli** [JetBrains/teamcity-aws-codedeploy-plugin#22]
Hi,

I would like to download and install the plugin but the documentation download link returns "does not exist".

Document:  https://confluence.jetbrains.com/display/TW/AWS+CodeDeploy+Runner
Latest nightly build link: https://teamcity.jetbrains.com/guestAuth/repository/download/TeamCityPluginsByJetBrains_AwsCodeDeployPlugin_AgainstTeamCityTrunk/.lastSuccessful/aws-codedeploy-plugin.zip?_ga=2.88767707.195393957.1573332226-1126293110.1566220865

Is there any link of the plugin ready to download?

**Comment by vbedrosova** [comment]
Hi, Ünal, I've fixed the Latest nightly build link. 
https://teamcity.jetbrains.com/repository/download/TeamCityPluginsByJetBrains_AwsCodeDeployPlugin_TestTeamCityTrunkJdk18/.lastSuccessful/aws-codedeploy-plugin.zip?_ga=2.190005283.94838732.1573466205-504381471.1569915300
