### ISSUE TITLE
No fields available on build step configuration page

### ISSUE THREAD

**Issue by magicxor** [JetBrains/teamcity-aws-codedeploy-plugin#23]
I have TeamCity 2019.1.5 (build 66605) + teamcity-aws-codedeploy-plugin SNAPSHOT-202001182317 on my build server. When I try to create the build step of type "AWS CodeDeploy", I see no configuration fields - there are no sections such as [Revision Location, CodeDeploy Application](https://blog.jetbrains.com/teamcity/2016/04/aws-codedeploy-runner-plugin/), etc. Therefore I just can't use this plugin:

![image](https://user-images.githubusercontent.com/8275793/75268570-9e8ef700-5832-11ea-8b0d-fe4012e5c135.png)

However I found teamcity-aws-codedeploy-plugin SNAPSHOT-201709181051 and it works great. I can't figure out what's the problem with my setup.
[aws-codedeploy-plugin_OLD_2017.zip](https://github.com/JetBrains/teamcity-aws-codedeploy-plugin/files/4251098/aws-codedeploy-plugin_OLD_2017.zip)

**Comment by burnasheva** [comment]
Hi @magicxor. 
Thank you for reporting it. I've created [the issue in YouTrack](https://youtrack.jetbrains.com/issue/TW-64664). Please, watch it to get all the updates.

**Comment by burnasheva** [comment]
@magicxor now you can download the necessary version on [the plugin repository](https://plugins.jetbrains.com/plugin/9018-aws-codedeploy/versions).

**Comment by burnasheva** [comment]
@magicxor now you can download the necessary version on [the plugin repository](https://plugins.jetbrains.com/plugin/9018-aws-codedeploy/versions).

**Comment by burnasheva** [comment]
@magicxor now you can download the necessary version on [the plugin repository](https://plugins.jetbrains.com/plugin/9018-aws-codedeploy/versions).
