### ISSUE TITLE
Elastic Beanstalk Support

### ISSUE THREAD

**Issue by rtfpessoa** [JetBrains/teamcity-aws-codedeploy-plugin#3]
Hi,

I was looking for any TeamCity plugin that could do Elastic Beanstalk deployments, but I could not find any.

The only thing I found was this repo, which I thought was a good starting point for me to implement it.

After some changes I got this working: https://github.com/rtfpessoa/teamcity-aws-elasticbeanstalk-plugin

Just passed by to thank you guys and let you know about it.

Note: I tried to give proper credit for the base work and kept all the license headers.

**Comment by vbedrosova** [comment]
Hi, Rodrigo, sorry for the delayed reply.
Thanks a lot for the plugin link, we'll verify it and share with other users.
