### ISSUE TITLE
Cannot use parameter for "S3 object key:"

### ISSUE THREAD

**Issue by pagemedias** [JetBrains/teamcity-aws-codedeploy-plugin#4]
When trying to just 'Deploy' using TeamCity CodeDeploy Plugin it is required to provide "S3 object key:".

When trying to provide parameter in "S3 object key:" field get the error:
```
S3 object key must contain only safe characters
```

**Comment by vbedrosova** [comment]
hi, sorry for the deplayed reply, [the issue](https://youtrack.jetbrains.com/issue/TW-46802) was fixed in one of the latest plugin builds

**Comment by pagemedias** [comment]
Thank you vbedrosova!
