### ISSUE TITLE
CloudFormation plugin

### ISSUE THREAD

**Issue by sjey** [JetBrains/teamcity-aws-codedeploy-plugin#5]
Hi,

I was looking for a CloudFormation teamcity plugin as I need it badly. So I thought I can make use of this repo and implement it for CloudFormation. 

I made some changes to code to support cloudformation and kept all the license headers as it is.  I can share the repository once the code is ready. 

I would like to thank you guys a lot and let you know that I am working on the cloud formation plugin.

**Comment by vbedrosova** [comment]
Hi, sjey, happy to hear that you are working on a new plugin. BTW we've just launched the TeamCity plugin contest https://plugins.jetbrains.com/contest/teamcity

**Comment by sjey** [comment]
Thanks for responding. Thats an awesome news. I will complete the code and submit it for review as well as in the competition as early as possible or before the deadline. Thanks once again vbedrosova.

**Comment by sjey** [comment]
Hi vbedrosova,

I finished the plugin development. Unfortunately I couldn't finish it during the contest.

https://github.com/sjey/teamcity-aws-cloudformation-plugin

I have also uploaded the plugin to pluginrepo at jetbrains.

**Comment by vbedrosova** [comment]
Hi sjey, nice to hear that! The plugin is feature in the TeamCity plugin list https://plugins.jetbrains.com/teamcity/plugin/9477-aws-cloudformation. Please make sure the data is correct.
