### ISSUE TITLE
Latest nightly build download link broken

### ISSUE THREAD

**Issue by JavierCane** [JetBrains/teamcity-aws-codedeploy-plugin#7]
Hi!

I would like to download and install the plugin but [the documentation](https://confluence.jetbrains.com/display/TW/AWS+CodeDeploy+Runner) download link (https://teamcity.jetbrains.com/guestAuth/repository/download/TeamCityPluginsByJetBrains_AwsCodeDeployPlugin_AgainstTeamCityTrunk/.lastSuccessful/aws-codedeploy-plugin.zip) returns a 404.

Is there any milestone or beta version of the plugin ready to download?

**Comment by VladRassokhin** [comment]
Hi @JavierCane,
I've rebuild plugin, so artifact is available now.
We had have incorrect cleanup rules configured for that run configuration.
