### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by ralsu091** [JetBrains/teamcity-aws-codedeploy-plugin#9]
Hello,

We have been using this plugin since the beginning of its release and it's great!
I see that the plugin is still in beta and I was wondering if any of the changes are breaking changes. Should we wait until it's out of Beta to update the plugin? It would be nice to have release notes whenever there is a new version.

Thanks!

**Comment by vbedrosova** [comment]
Hi, @ralsu091! Sorry for the delay. Though the plugin is in Beta, we normally do not commit breaking changes and you'll be able to use it (or newer versions) once you've installed and configured it on your server.
